version: '3.7'

services:
  jenkins-server:
    image: localhost:5000/jenkins-server
    container_name: jenkins-server
    volumes:
      - jenkins-home:/var/jenkins_home
    ports:
      - '8080:8080'
      - '50000:50000'
    build:
      context: ./jenkins/server/
      dockerfile: Dockerfile

  jenkins-slave:
    image: localhost:5000/jenkins-slave
    container_name: jenkins-slave
    environment:
      - 'JENKINS_URL=http://jenkins-server:8080'
    build:
      context: ./jenkins/agent/
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins-server

volumes:
  jenkins-home:
