version: '3.7'

services:
  teamcity-server:
    image: jetbrains/teamcity-server:latest
    container_name: teamcity-server
    volumes:
      - teamcity-server-datadir:/data/teamcity-server/datadir
      - teamcity-server-logs:/opt/teamcity/logs
    ports:
      - 8111:8111

  teamcity-agent:
    image: localhost:5000/teamcity-docker-compose:latest
    container_name: teamcity-agent
    build:
      context: .
      dockerfile: ./teamcity/agent/Dockerfile
    environment:
      SERVER_URL: http://teamcity-server:8111
    volumes:
      - teamcity-agent-conf:/data/teamcity_agent/conf
      - /opt/buildagent/work:/opt/buildagent/work
      - /opt/buildagent/temp:/opt/buildagent/temp
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - teamcity-server
            
volumes:
  teamcity-server-datadir:
  teamcity-server-logs:
  teamcity-agent-conf: